server:
  port: 80
spring:
  security:
    jwt:
      key: abcde
      expire: 3
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/note_test_db
    username: root
    password: 123456